const CFG=window.WALKGOO_CONFIG||{};
function favs(){return JSON.parse(localStorage.getItem('walkgoo_favs')||'[]')}
function isFav(id){return favs().includes(id)}
function toggleFav(id){const a=favs();const i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);localStorage.setItem('walkgoo_favs',JSON.stringify(a));return a.includes(id)}
function normalizeTourItem(item,themeId){return {id:'api-'+(item.contentid||crypto.randomUUID()),themeId,title:item.title||'이름 없음',region:[item.addr1,item.addr2].filter(Boolean).join(' '),summary:item.addr1||'한국관광공사 TourAPI 검색 결과',image:item.firstimage||item.firstimage2||'',difficulty:'정보 확인 필요',duration:'정보 확인 필요',distance:'정보 확인 필요',parking:'정보 확인 필요',toilet:'정보 확인 필요',lat:Number(item.mapy)||0,lng:Number(item.mapx)||0,tags:['TourAPI','동적데이터'],description:item.addr1||'',points:['상세 정보는 관광공사 데이터 기준으로 보강 가능'],cautions:['운영 정보는 방문 전 확인 필요'],external:true,contentid:item.contentid};}
async function fetchTourApi(keyword='둘레길',themeId='trail'){if(!CFG.TOUR_API_KEY)return[];const url=new URL(CFG.TOUR_API_BASE+'/searchKeyword2');url.search=new URLSearchParams({serviceKey:CFG.TOUR_API_KEY,MobileOS:'ETC',MobileApp:'WalkGoo',_type:'json',numOfRows:'9',pageNo:'1',arrange:'O',keyword});try{const r=await fetch(url);const j=await r.json();let items=j?.response?.body?.items?.item||[];if(!Array.isArray(items))items=[items];return items.map(x=>normalizeTourItem(x,themeId));}catch(e){console.warn(e);return[]}}
async function aiRecommend(prompt,places){if(CFG.AI_PROXY_URL){try{const r=await fetch(CFG.AI_PROXY_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,places})});const j=await r.json();return j.answer||j.message||'AI 응답을 해석하지 못했습니다.'}catch(e){return 'AI 프록시 호출 중 오류가 발생했습니다. '+e.message}}
const q=(prompt||'').toLowerCase();let list=places.filter(p=>[p.title,p.region,p.summary,(p.tags||[]).join(' ')].join(' ').toLowerCase().includes(q));if(!list.length){if(q.includes('오름')||q.includes('제주'))list=places.filter(p=>p.themeId==='oreum');else if(q.includes('섬')||q.includes('바다'))list=places.filter(p=>p.themeId==='island');else list=places.filter(p=>p.themeId==='trail');}
return list.slice(0,3).map((p,i)=>`${i+1}. ${p.title}\n- 지역: ${p.region}\n- 난이도/시간: ${p.difficulty} / ${p.duration}\n- 추천 이유: ${p.summary}`).join('\n\n')||'조건에 맞는 추천지가 없습니다.'}
function cardHtml(p){return `<article class="place-card"><a href="detail.html?id=${encodeURIComponent(p.id)}"><div class="thumb">${p.image?`<img src="${p.image}" alt="${p.title}">`:''}<span>${p.tags?.[0]||'WalkGoo'}</span></div></a><div class="place-body"><h3>${p.title}</h3><p>${p.summary}</p><div class="meta"><b>${p.region}</b><b>${p.difficulty}</b><b>${p.duration}</b></div><div class="card-actions"><a class="btn primary" href="detail.html?id=${encodeURIComponent(p.id)}">상세보기</a><button class="btn fav-btn" data-id="${p.id}">${isFav(p.id)?'★ 저장됨':'☆ 즐겨찾기'}</button></div></div></article>`}
