let allPlaces=[...PLACES];
const themeGrid=document.getElementById('themeGrid'),placeGrid=document.getElementById('placeGrid');
function renderThemes(){themeGrid.innerHTML=THEMES.map(t=>`<button class="theme-card" data-theme="${t.id}"><div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p></button>`).join('');document.querySelectorAll('.theme-card').forEach(b=>b.onclick=()=>filterPlaces(b.dataset.theme));}
function renderPlaces(list=allPlaces){placeGrid.innerHTML=list.map(cardHtml).join('')||'<p>표시할 데이터가 없습니다.</p>';document.querySelectorAll('.fav-btn').forEach(b=>b.onclick=()=>{toggleFav(b.dataset.id);renderPlaces(list)});}
function filterPlaces(theme){document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c.dataset.filter===theme));renderPlaces(theme==='all'?allPlaces:allPlaces.filter(p=>p.themeId===theme));document.getElementById('places').scrollIntoView({behavior:'smooth'});}
document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>filterPlaces(c.dataset.filter));
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();const q=document.getElementById('searchInput').value.trim().toLowerCase();renderPlaces(allPlaces.filter(p=>[p.title,p.region,p.summary,(p.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));document.getElementById('places').scrollIntoView({behavior:'smooth'});};
document.getElementById('aiButton').onclick=async()=>{const v=document.getElementById('aiPrompt').value.trim();document.getElementById('aiResult').textContent='추천을 만드는 중입니다...';document.getElementById('aiResult').textContent=await aiRecommend(v,allPlaces)};
async function init(){renderThemes();renderPlaces();const apiData=[...(await fetchTourApi('둘레길','trail')),...(await fetchTourApi('섬 여행','island')),...(await fetchTourApi('제주 오름','oreum'))];if(apiData.length){allPlaces=[...PLACES,...apiData];renderPlaces(allPlaces)}}init();
